/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyquancafe_QuanLy;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import Models.Detail;
import quanlyquancafe_view.quanlyquancafe_Main;
/**
 *
 * @author Hoang Quan
 */
public class QuanLy extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy
     */
     private Detail detail;
    public QuanLy(Detail d) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        detail = new Detail(d);
        BTN_QLHH.setBorder(BorderFactory.createLineBorder((Color.black)));
        BTN_QLB.setBorder(null);
        BTN_QLNV.setBorder(null);
        jpQLHH qlhh = new jpQLHH();
        qlhh.setSize(1050,650);
        jPanel7.removeAll();
        jPanel7.add(qlhh);
        jPanel7.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_home = new javax.swing.JLabel();
        BTN_QLNV = new keeptoo.KButton();
        BTN_QLB = new keeptoo.KButton();
        BTN_QLHH = new keeptoo.KButton();
        BTN_QLLHH = new keeptoo.KButton();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 107, 135)));
        kGradientPanel1.setkEndColor(new java.awt.Color(102, 165, 173));
        kGradientPanel1.setkStartColor(new java.awt.Color(196, 223, 230));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(51, 107, 135)));

        jPanel5.setBackground(new java.awt.Color(51, 107, 135));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quản Lý");

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyquancafe_image/icons8_back_arrow_50px.png"))); // NOI18N
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(btn_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(54, 54, 54))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_home)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BTN_QLNV.setText("QUẢN LÝ NHÂN VIÊN");
        BTN_QLNV.setkEndColor(new java.awt.Color(224, 255, 255));
        BTN_QLNV.setkHoverEndColor(new java.awt.Color(176, 224, 230));
        BTN_QLNV.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        BTN_QLNV.setkHoverStartColor(new java.awt.Color(16, 78, 139));
        BTN_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_QLNVActionPerformed(evt);
            }
        });

        BTN_QLB.setText("QUẢN LÝ BÀN");
        BTN_QLB.setkEndColor(new java.awt.Color(224, 255, 255));
        BTN_QLB.setkHoverEndColor(new java.awt.Color(176, 224, 230));
        BTN_QLB.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        BTN_QLB.setkHoverStartColor(new java.awt.Color(16, 78, 139));
        BTN_QLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_QLBActionPerformed(evt);
            }
        });

        BTN_QLHH.setText("QUẢN LÝ HÀNG HÓA");
        BTN_QLHH.setkEndColor(new java.awt.Color(224, 255, 255));
        BTN_QLHH.setkHoverEndColor(new java.awt.Color(176, 224, 230));
        BTN_QLHH.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        BTN_QLHH.setkHoverStartColor(new java.awt.Color(16, 78, 139));
        BTN_QLHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_QLHHActionPerformed(evt);
            }
        });

        BTN_QLLHH.setText("LOẠI HÀNG HÓA");
        BTN_QLLHH.setkEndColor(new java.awt.Color(224, 255, 255));
        BTN_QLLHH.setkHoverEndColor(new java.awt.Color(176, 224, 230));
        BTN_QLLHH.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        BTN_QLLHH.setkHoverStartColor(new java.awt.Color(16, 78, 139));
        BTN_QLLHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_QLLHHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_QLLHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_QLHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_QLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(BTN_QLHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BTN_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BTN_QLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BTN_QLLHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        quanlyquancafe_Main home = new quanlyquancafe_Main(detail);
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_btn_homeMousePressed

    private void BTN_QLHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_QLHHActionPerformed
        BTN_QLHH.setBorder(BorderFactory.createLineBorder((Color.black)));
        BTN_QLB.setBorder(null);
        BTN_QLNV.setBorder(null);
        BTN_QLLHH.setBorder(null);
        jpQLHH qlhh = new jpQLHH();
        qlhh.setSize(1050,650);
        jPanel7.removeAll();
        jPanel7.add(qlhh);
        jPanel7.updateUI();
    }//GEN-LAST:event_BTN_QLHHActionPerformed

    private void BTN_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_QLNVActionPerformed
        BTN_QLNV.setBorder(BorderFactory.createLineBorder((Color.black)));
        BTN_QLB.setBorder(null);
        BTN_QLHH.setBorder(null);
        BTN_QLLHH.setBorder(null);
        jpQLNV qlnv = new jpQLNV(detail);
        qlnv.setSize(1050,650);
        jPanel7.removeAll();
        jPanel7.add(qlnv);
        jPanel7.updateUI();
    }//GEN-LAST:event_BTN_QLNVActionPerformed

    private void BTN_QLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_QLBActionPerformed
        BTN_QLB.setBorder(BorderFactory.createLineBorder((Color.black)));
        BTN_QLLHH.setBorder(null);
        BTN_QLHH.setBorder(null);
        BTN_QLNV.setBorder(null);
        jpBan qlb = new jpBan();
        qlb.setSize(1050,650);
        jPanel7.removeAll();
        jPanel7.add(qlb);
        jPanel7.updateUI();
    }//GEN-LAST:event_BTN_QLBActionPerformed

    private void BTN_QLLHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_QLLHHActionPerformed
        BTN_QLLHH.setBorder(BorderFactory.createLineBorder((Color.black)));
        BTN_QLB.setBorder(null);
        BTN_QLHH.setBorder(null);
        BTN_QLNV.setBorder(null);
        jpLHH qllhh = new jpLHH(detail);
        qllhh.setSize(1050,650);
        jPanel7.removeAll();
        jPanel7.add(qllhh);
        jPanel7.updateUI();
    }//GEN-LAST:event_BTN_QLLHHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Detail detail= new Detail();
//                if(detail.getRoll().equals("3")){
//                   new quanlyquancafe_Main(detail).setVisible(false);
//                   Login login = new Login();
//                   login.setVisible(true);
//                }else{
                new QuanLy(detail).setVisible(true);
                }
//            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton BTN_QLB;
    private keeptoo.KButton BTN_QLHH;
    private keeptoo.KButton BTN_QLLHH;
    private keeptoo.KButton BTN_QLNV;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
